### ISSUE TITLE
Webpack compilation plugin not working with nativescript-webpack 0.10.2

### ISSUE THREAD

**Issue by isaacfi** [nabil-mansouri/nativescript-couchbaselite#6]
When I build with webpack enabled:

**tns build android --bundle**

The plugin has an error compilation:

```
ERROR in ../node_modules/nativescript-couchbaselite/commons.ts
Module build failed: Error: **$PATH**/commons.ts is missing fromthe TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at NativeScriptAngularCompilerPlugin.getCompiledFile (**$PATH**/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:663:23)
    at NativeScriptAngularCompilerPlugin.getCompiledFile (**$PATH**/node_modules/nativescript-dev-webpack/plugins/NativeScriptAngularCompilerPlugin.ts:76:22)
    at plugin.done.then (**$PATH**/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ../node_modules/nativescript-couchbaselite/index.js 5:16-36 6:16-36
 @ ./services/couchbase.instance.ts
 @ ./modules/app.module.ts
 @ ./main.ts
```
I don´t know how to include the commons.ts file to the webpack compilation. This is my package.json:

{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.test",
    "tns-ios": {
      "version": "4.0.1"
    },
    "tns-android": {
      "version": "4.0.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~5.2.0",
    "@angular/common": "~5.2.0",
    "@angular/compiler": "~5.2.0",
    "@angular/core": "~5.2.0",
    "@angular/forms": "~5.2.0",
    "@angular/http": "~5.2.0",
    "@angular/platform-browser": "~5.2.0",
    "@angular/platform-browser-dynamic": "~5.2.0",
    "@angular/router": "~5.2.0",
    "@types/lodash": "^4.14.88",
    "angular2-uuid": "^1.1.1",
    "lodash": "^4.17.4",
    "moment": "^2.18.1",
    "nativescript-angular": "~5.2.0",
    "nativescript-appavailability": "^1.3.1",
    "nativescript-barcodescanner": "^2.7.6",
    "nativescript-bluetooth": "^1.3.0",
    "nativescript-camera": "^3.2.1",
    "nativescript-cardview": "^3.0.1",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-contacts": "^1.5.4",
    "nativescript-couchbaselite": "^1.0.11",
    "nativescript-drop-down": "^3.2.4",
    "nativescript-enumerable": "^3.5.2",
    "nativescript-geolocation": "3.0.1",
    "nativescript-google-maps-sdk": "^2.6.0",
    "nativescript-imagecropper": "^0.1.2",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-local-notifications": "^2.0.3",
    "nativescript-modal-datetimepicker": "^1.0.3",
    "nativescript-ngx-fonticon": "^4.0.0",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "^1.3.1",
    "nativescript-plugin-firebase": "5.1.8",
    "nativescript-pro-ui": "3.3.0",
    "nativescript-sqlite": "file:nativescript-sqlite-commercial-1.1.6.tgz",
    "nativescript-swift-3.0": "^1.0.0",
    "nativescript-telephony": "^1.0.4",
    "nativescript-textinputlayout": "file:nativescript-textinputlayout-2.0.2.tgz",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.5.0",
    "tns-core-modules": "^4.0.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.2.0",
    "@ngtools/webpack": "~1.9.4",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "chai": "^3.5.0",
    "clean-webpack-plugin": "~0.1.19",
    "codelyzer": "^4.0.0",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "filewalker": "0.1.3",
    "karma": "^1.6.0",
    "karma-chai": "^0.1.0",
    "karma-mocha": "^1.3.0",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "mocha": "^3.3.0",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-custom-entitlements": "^0.2.0",
    "nativescript-dev-typescript": "^0.6.0",
    "nativescript-dev-webpack": "^0.10.2",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "tns-platform-declarations": "3.4.0",
    "tslib": "1.7.1",
    "tslint": "^5.1.0",
    "typescript": "~2.6.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  },
  "scripts": {
    "tslint": "tslint --project tsconfig.json --config tslint.json",
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install"
  }
}

**Comment by isaacfi** [comment]
I had to use this [nativescript-couchbase](https://github.com/couchbaselabs/nativescript-couchbase) plugin instead of yours and it works like a charm.

**Comment by skopekreep** [comment]
Also seeing the same errors.  Any thoughts?

**Comment by nabil-mansouri** [comment]
Hi , it looks like you are trying to bundle my plugin from source (while it is already bundled, source are not distributed). I need to check but it seems to be that.

**Comment by matt-psaltis** [comment]
The problem stems from the npm bundle including the commons.ts file. If you manually delete the file from the node_modules folder it compiles. I'm still trying to work out the correct webpack config change to make as an exclusion rule does not seem to be taking effect.

**Comment by skopekreep** [comment]
Adding this to references.d.ts seemed to resolve the issue for me:

`/// <reference path="./node_modules/nativescript-couchbaselite/commons.ts" />`

**Comment by matt-psaltis** [comment]
I'm getting errors using this approach as the commons.ts file contains a concrete class which violates the typescript definition format.  What I'm thinking is, the packaging process of nativescript-couchbaselite should be including a commons.d.ts definition file instead of the commons.ts source file - thoughts?

**Comment by isaacfi** [comment]
I've found another solution. You can to create a js file in hooks/before-prepare called nativescript-couchbaselite.js with this:

```
var fs = require('fs');

module.exports = function($logger) {
    var commonsTSFile = 'node_modules/nativescript-couchbaselite/commons.ts';
    console.log('Adding commons.ts for nativescript-couchbaselite');
    if (fs.existsSync(commonsTSFile)) {
        fs.unlink(commonsTSFile);
    }
};
```

Regards
